Добавлены рекомендации в контроллер и клиент
software-sales-and-installations/softplat-back pull request #162
Opened 2023-12-08 15:25 UTC by mdemidkin1992

* Добавлен путь для получения рекомендаций покупателю в BuyerClient и BuyerController
* Добавлены тесты по фиче

2023-12-09 13:25 UTC, Wereflyers requested changes

2023-12-09 13:25 UTC, Wereflyers commented on ssai-main/ssai-main-client/src/main/java/ru/softplat/main/client/user/BuyerClient.java
> +    public ResponseEntity<Object> getRecommendations(long userId, int minId, int pageSize) {
Они есть, но в контроллерах продукта. Если хочешь добавлять, то удаляй те.

2023-12-11 09:34 UTC, mdemidkin1992 commented on ssai-main/ssai-main-client/src/main/java/ru/softplat/main/client/user/BuyerClient.java
> +    public ResponseEntity<Object> getRecommendations(long userId, int minId, int pageSize) {
Да, точно, не заметил

2023-12-11 12:12 UTC, Wereflyers approved these changes

2023-12-12 18:30 UTC, Wereflyers commented on ssai-main/ssai-main-server/src/main/java/ru/softplat/main/server/repository/buyer/FavoriteRepository.java
> +            "GROUP BY f.product.id, f.product.productionTime " +
разве нужно группировать по времени публикации?

2023-12-14 08:29 UTC, mdemidkin1992 commented on ssai-main/ssai-main-server/src/main/java/ru/softplat/main/server/repository/buyer/FavoriteRepository.java
> +            "GROUP BY f.product.id, f.product.productionTime " +
убрал, работает, выходит, что нет)

2023-12-14 13:01 UTC, merged

2023-12-15 20:48 UTC, nkorzh commented on ssai-main/ssai-main-server/src/test/java/ru/softplat/main/server/web/controller/AbstractControllerTest.java
> +        for (int i = 0; i < expect.size(); i++) {
точно есть assertEquals который сравнивает списки

2023-12-15 20:48 UTC, nkorzh commented on ssai-main/ssai-main-server/src/test/java/ru/softplat/main/server/web/controller/user/BuyerRecommendationsTest.java
> +        List<ProductResponseDto> expect = getProductsByIds(List.of(3L, 5L));
actual это when

2023-12-15 20:48 UTC, nkorzh commented on ssai-main/ssai-main-server/src/test/java/ru/softplat/main/server/web/controller/user/BuyerRecommendationsTest.java
> +        List<ProductResponseDto> expect = getProductsByIds(List.of(3L, 5L));
вот этот вызов смущает: откуда метод? правильно ли он работает что мы с ним сравниваем?