Add images
software-sales-and-installations/softplat-back pull request #53
Opened 2023-11-04 18:42 UTC by mdemidkin1992

2023-11-04 20:56 UTC, mikhailovPI requested changes, later dismissed
ProductResponseDto уже были поправлены в моем PR. Также исправлены логи. Обнови свою ветку dev, согласно моим изменениям вчерашним, а потом обнови свой PR.

2023-11-04 21:56 UTC, Wereflyers reviewed
Тебе нужно памятник за эту работу поставить.
Но проверять это нереально. Главное, что тесты проходят.

2023-11-04 21:56 UTC, Wereflyers commented on src/main/java/ru/yandex/workshop/main/dto/seller/SellerMapper.java
> +    }
Уверен, что нужны все эти дополнительные методы, если уже есть реализованный маппер? Смотрел в реализации?

2023-11-04 21:56 UTC, Wereflyers commented on src/main/java/ru/yandex/workshop/main/service/vendor/VendorServiceImpl.java
> +        vendorRepository.deleteById(vendorId);
Если будет удаляться, картинка удалится?

2023-11-04 21:56 UTC, Wereflyers commented on src/main/java/ru/yandex/workshop/main/dto/product/ProductDto.java
>      LocalDateTime productionTime;
Едва ли нужно для создания или обновления

2023-11-04 21:56 UTC, Wereflyers commented on src/main/java/ru/yandex/workshop/main/dto/product/ProductDto.java
> +    Long seller;
Не нужно его указывать. Продавец - это тот, кто создает/редактирует карточку.

2023-11-05 09:09 UTC, mdemidkin1992 commented
@mikhailovPI Ответы на твои коммменты:

> 1. Обнови свою ветку dev, согласно моим изменениям вчерашним, а потом обнови свой PR.

Уже вчера сделано, твои изменения из dev спуллены, изменения учеты, конфликты версий решены – смотри последний коммит в этом PR [d19058f](https://github.com/software-sales-and-installations/softplat-back/pull/53/commits/d19058f1d7c2924a6341290e6cf2c774809dbe68)

> 2. ProductResponseDto уже были поправлены в моем PR. 

ProductResponseDto у нас одинаково был реализован. Основной объем работ в этом PR был посвящен ProductDto, который получаем при создании / обновлении продукта. Его облегчил, поскольку мы не можем ожидать от фронта, что будет приходить полностью заполненный объект, включая Seller, Vendor и тд. Достаточно передать на вход их ```id```, Hibernate сделает остальное через связи. 

> 3. Также исправлены логи. 

Логи везде в твоей реализации, смотри последний коммит.

2023-11-05 09:12 UTC, mdemidkin1992 commented on src/main/java/ru/yandex/workshop/main/dto/seller/SellerMapper.java
> +    }
У меня без них не запускалось, попробую еще раз

2023-11-05 09:14 UTC, mdemidkin1992 commented on src/main/java/ru/yandex/workshop/main/service/vendor/VendorServiceImpl.java
> +        vendorRepository.deleteById(vendorId);
У нас не прописано в БД условие cascade, по идее должно сохраниться

2023-11-05 09:18 UTC, mdemidkin1992 commented on src/main/java/ru/yandex/workshop/main/dto/product/ProductDto.java
>      LocalDateTime productionTime;
Надо уточнить у Паши, если это дата публикации продукта (после модерации админом), то да, на вход это не должно поступать

2023-11-05 09:20 UTC, mdemidkin1992 commented on src/main/java/ru/yandex/workshop/main/dto/product/ProductDto.java
> +    Long seller;
Надо вообще подумать, как мы хотим передавать id пользователя, который направляет запрос, возможно это стоит делать в header к запросу, не параметрах запроса или переменная пути

2023-11-05 09:39 UTC, Wereflyers commented on src/main/java/ru/yandex/workshop/main/service/vendor/VendorServiceImpl.java
> +        vendorRepository.deleteById(vendorId);
Нужно удалять

2023-11-05 09:40 UTC, Wereflyers commented on src/main/java/ru/yandex/workshop/main/dto/product/ProductDto.java
>      LocalDateTime productionTime;
Мы говорили об это при проектировании БД. Это она

2023-11-05 09:41 UTC, Wereflyers commented on src/main/java/ru/yandex/workshop/main/dto/product/ProductDto.java
> +    Long seller;
Я убеждена, что это в любом случае будет отдельно от дто. А как - решит Security)

2023-11-05 09:41 UTC, Wereflyers commented on src/main/java/ru/yandex/workshop/main/dto/product/ProductDto.java
> +    Long seller;
Если для жтого надо код править - закинь пока емейл в header, например

2023-11-05 11:30 UTC, Wereflyers commented on src/main/java/ru/yandex/workshop/main/dto/product/ProductDto.java
> +    Long seller;
Можешь вообще не трогать, займусь сама

2023-11-05 11:48 UTC, mikhailovPI reviewed
См комментарии. Небольшие вопросы возникли

2023-11-05 11:48 UTC, mikhailovPI commented on src/main/java/ru/yandex/workshop/main/model/product/ProductStatus.java
> +    USA("USA");
Думаю этого тут не должно быть

2023-11-05 11:48 UTC, mikhailovPI commented on src/main/java/ru/yandex/workshop/main/dto/product/ProductDto.java
> +    Long seller;
Думаю это vendor с security должен подбираться. Нужно запомнить кто авторизовался.

2023-11-05 11:48 UTC, mikhailovPI commented on src/main/java/ru/yandex/workshop/main/model/image/Image.java
> +    private Long size;
В каких единицах измерения ты это передаешь? В байтах?
Или это какой-то другой size?

2023-11-05 11:48 UTC, mikhailovPI commented on src/main/java/ru/yandex/workshop/main/service/product/ProductService.java
> +    private final ImageService imageService;
может обращаться к ImageRepository?

2023-11-05 11:48 UTC, mikhailovPI commented on src/main/java/ru/yandex/workshop/main/service/vendor/VendorServiceImpl.java
> +    private final ImageService imageService;
Тут тоже Repository надо

2023-11-05 11:48 UTC, mikhailovPI commented on src/main/java/ru/yandex/workshop/main/service/vendor/VendorServiceImpl.java
> +        vendorRepository.deleteById(vendorId);
Тогда, по идее, можно подбирать метод deleteImage из репы

2023-11-05 13:37 UTC, pankkovv approved these changes

2023-11-05 14:47 UTC, mdemidkin1992 commented on src/main/java/ru/yandex/workshop/main/model/image/Image.java
> +    private Long size;
Да, например сейчас у меня в базе image картинка с size 10642, это примерно 11 KB

2023-11-05 14:48 UTC, mdemidkin1992 commented on src/main/java/ru/yandex/workshop/main/model/image/Image.java
> +    private Long size;
Опирался на эту статью, когда проектировал сервис для Image
https://frontbackend.com/spring-boot/spring-boot-upload-file-to-postgresql-database

2023-11-05 14:51 UTC, mdemidkin1992 commented on src/main/java/ru/yandex/workshop/main/service/product/ProductService.java
> +    private final ImageService imageService;
Смотри, я думал об этом, но тогда для каждой картинки надо будет в каждом сервисе (VendorService, SellerService, ProductService) реализовывать одни и те же методы для конвертирования файла MultipartFile в Image чтобы сохранить в БД, и по преобразованию в byte[], когда ее оттуда достаем. 

Поэтому решил реализовать эти методы отдельно в сервисе ImageService и его уже инжектить как вспомогательный сервис в VendorService, SellerService и ProductService.

2023-11-05 14:52 UTC, mdemidkin1992 commented on src/main/java/ru/yandex/workshop/main/service/vendor/VendorServiceImpl.java
> +    private final ImageService imageService;
Будет имхо не очень удобно т.к. придется одни и те же методы по преобразованию картинок реализовывать в каждом сервисе VendorService, SellerService и ProductService

2023-11-05 15:00 UTC, mdemidkin1992 commented on src/main/java/ru/yandex/workshop/main/service/vendor/VendorServiceImpl.java
> +        vendorRepository.deleteById(vendorId);
@mikhailovPI Паша, не понял про "подбирать метод deleteImage из репы", что ты предлагаешь?

2023-11-05 15:03 UTC, mdemidkin1992 commented on src/main/java/ru/yandex/workshop/main/model/product/ProductStatus.java
> +    USA("USA");
Согласен, уберу, не знаю, как это тут оказалось)

2023-11-05 15:07 UTC, mdemidkin1992 commented on src/main/java/ru/yandex/workshop/main/service/vendor/VendorServiceImpl.java
> +        vendorRepository.deleteById(vendorId);
Могу добавить в настройки schema.sql констрэйнты к FK таблиц seller, vendor и product, что on delete cascade чтобы при удалении сущности image тоже удалялся, и дополнительно в ImageService метод deleteImageById(), так подойдет?

2023-11-05 15:08 UTC, mdemidkin1992 commented on src/main/java/ru/yandex/workshop/main/dto/product/ProductDto.java
> +    Long seller;
Тогда оставляю как есть

2023-11-05 15:08 UTC, mdemidkin1992 commented on src/main/java/ru/yandex/workshop/main/dto/product/ProductDto.java
>      LocalDateTime productionTime;
Тогда тоже убираю это поле

2023-11-05 15:52 UTC, mikhailovPI commented on src/main/java/ru/yandex/workshop/main/service/vendor/VendorServiceImpl.java
> +        vendorRepository.deleteById(vendorId);
Имел ввиду вызвать метод deleteById(id) из ImageRepository

2023-11-05 16:03 UTC, mdemidkin1992 commented on src/main/java/ru/yandex/workshop/main/dto/seller/SellerMapper.java
> +    }
Не выходит без доп методов, оставляю

2023-11-05 17:05 UTC, Wereflyers approved these changes

2023-11-05 19:35 UTC, merged